### ISSUE TITLE
Thread-14/WARN

### ISSUE THREAD

**Issue by Chypik** [plasmoapp/plasmo-voice#146]
Paper-77 (MC: 1.18.1)

```
[16:17:36] [Thread-14/WARN]: java.lang.IllegalArgumentException: Invalid UUID string: 
[16:17:36] [Thread-14/WARN]: 	at java.base/java.util.UUID.fromString1(UUID.java:280)
[16:17:36] [Thread-14/WARN]: 	at java.base/java.util.UUID.fromString(UUID.java:258)
[16:17:36] [Thread-14/WARN]: 	at plasmovoice-server-1.0.8.jar//su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
[16:17:36] [Thread-14/WARN]: 	at plasmovoice-server-1.0.8.jar//su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
[16:17:36] [Thread-14/WARN]: 	at plasmovoice-server-1.0.8.jar//su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:100)
```

**Comment by Toldoven** [comment]
Fixed in 1.0.9 

https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.9-spigot
