### ISSUE TITLE
Crash on minecraft launch

### ISSUE THREAD

**Issue by Bizzonium** [plasmoapp/plasmo-voice#203]
Plasmo voice prevents minecraft to launch second time after successful one until Plasmo-voice config get removed on path: 
```%USERPROFILE%\curseforge\minecraft\Instances\<profile>\config\PlasmoVoice\config.json```

![image](https://user-images.githubusercontent.com/8555356/168669513-aeb6d2f6-b113-414b-8aec-7d5e95f19e0b.png)

<details>
  <summary>Crash summary</summary>

```java

---- Minecraft Crash Report ----
// My bad.

Time: 5/16/22 10:40 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'plasmo_voice'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$8943/274174845.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	at net.minecraft.class_2588.fixKey(class_2588.java:529)
	at net.minecraft.class_2588.handler$eeg000$modify(class_2588.java:520)
	at net.minecraft.class_2588.<init>(class_2588.java:34)
	at su.plo.voice.client.config.ClientConfig$KeyBinding.<init>(ClientConfig.java:425)
	at su.plo.voice.client.config.ClientConfig$KeyBindingConfigEntry.deserialize(ClientConfig.java:387)
	at su.plo.voice.client.config.ClientConfig$KeyBindingConfigEntry.deserialize(ClientConfig.java:332)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at su.plo.voice.client.config.ClientConfig.read(ClientConfig.java:98)
	at su.plo.voice.client.VoiceClient.initialize(VoiceClient.java:63)
	at su.plo.voice.client.VoiceClientFabric.onInitializeClient(VoiceClientFabric.java:29)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$7676/1950315317.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$8943/274174845.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1078294520 bytes (1028 MB) / 2507145216 bytes (2391 MB) up to 15957229568 bytes (15218 MB)
	CPUs: 16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17120m -Xms256m
	Mixins in Stacktrace: ~~ERROR~~ NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()
	Fabric Mods: 
		addendum: Addendum 1.16.5-1.0.2
		adorn: Adorn 1.14.2+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.3
		advdebug: Advancements Debug 2.3.0
		ae2wtlib: AE2WTLib ${version}
		alaskanativecraft: Alaska Native Craft 1.2.2
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 2.3.0+mc1.16.5
		appliedenergistics2: Applied Energistics 2 8.4.0-alpha.3
		architectury: Architectury 1.29.50
		armorsoundtweak: Armor Sound Tweak 3.1.1
		artifacts: Artifacts 4.0.3+fabric
		artifice: Artifice 0.14.6+1.16.5
		attributefix: Attribute Fix {FABRIC} 1.0.2
		authme: Auth Me 2.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks 2.0.5
		bannerpp: Banner++ 2.0.3-snapshot+mc.1.16.2-rc1
		battletowers: Battle Towers 3.3.4-1.16.4
		bclib: BCLib 0.1.45
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdungeons: YUNG's Better Dungeons 1.16.5-1.0.1
		betterend: Better End 0.9.8.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betterpingdisplay: Better Ping Display 1.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		bitsandchisels: BitsAndChisels 2.3.2
		blast: BLAST 1.5.2
		blockshifter: Blockshifter 1.4.0+fabric-1.16.4
		blockus: Blockus 2.1.12+1.16.5
		blue_endless_jankson: jankson 1.2.0
		boringbackgrounds: Boring Backgrounds 3.0.2+1.16.3
		breakprogress: Break Progress 1.0.1
		builtinservers: Builtin Servers 1.0-BETA
		byg: BYG 1.1.8
		campanion: Campanion 1.3.5
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		carrier: Carrier 1.7.6
		cavebiomes: Cave Biomes 0.6.2
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		cherishedworlds: Cherished Worlds 2.0.1-1.16.5
		chillager_mod: Chillager 1.1
		chunky: Chunky 1.2.54
		cinderscapes: Cinderscapes 1.4.0
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.6.59
		cloth-armor-api-v1: Cloth Armor API v1 1.6.59
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-common-events-v1: Cloth Common Events v1 1.6.59
		cloth-config2: Cloth Config v4 4.13.49
		cloth-datagen-api-v1: Cloth Datagen v1 1.6.59
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.6.59
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.6.59
		cloth-scissors-api-v1: Cloth Scissors API v1 1.6.59
		cloth-utils-v1: Cloth Utils v1 1.6.59
		colorfulcolumns: Colorful Columns 1.0.0
		columns: Columns 1.1.1
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_github_nathanpb_safer: Safer 1.1.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:Restitched 1.96.3
		conjuring: Conjuring 0.2.5
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.4.0
		croptosis: Croptosis 1.1.0
		crusade: Crusade 1.2.1
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: DarkPaintings 3.0.4
		dawn: Dawn API 1.8
		de_javagl_obj: obj 0.3.0
		decimal_coins: Decimal Coins 1.16.5-1.3.0
		defaultsettings: DefaultSettings 3.0.2
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.3-beta1
		drinkbeer: Drink Beer 3.0.2
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.14
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		dynamicfps: Dynamic FPS 2.0.2
		ecotones: Ecotones 0.7.2
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchdesc: EnchantmentDescriptions 2.0.8
		entitybanners: Entity Banners 1.0-BETA
		expandability: ExpandAbility 2.0.1
		expandedstorage: Expanded Storage 7.3.7
		extragenerators: Extra Generators 1.0.3-BETA+1.16
		ezpas: Ezpas 1.2.2-1.16.5
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-language-scala: Fabric Language Scala 2.0.0+scala.3.0.2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.12
		fallflyinglib: FallFlyingLib 2.0.4
		fasttransferlib: Fast Transfer Lib 0.4.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.221
		fermion-gui: Fermion GUI 2.5.221
		fermion-modkeys: Fermion Modifier Keys 1.10.221
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-simulator: Fermion Simulator 1.8.221
		fermion-varia: Fermion Varia 2.6.221
		ferritecore: FerriteCore 2.1.0
		ffl-trinkets-compat: FFL Trinkets Compat 1.0.0
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		flytre_lib: FlytreLib 0.2.11
		fpsreducer: FPS Reducer 1.24-mc1.16.5
		frex: FREX 4.8.209
		ftbchunks: FTB Chunks 1605.3.2-build.115
		ftblibrary: FTB Library 1605.3.4-build.90
		ftbquests: FTB Quests 1605.3.6-build.76
		ftbteams: FTB Teams 1605.2.3-build.40
		gateofbabylon: Gate Of Babylon 1.4.4-1.16.5
		geckolib3: Geckolib 3.0.67
		givemehats: Give Me Hats! 1.5.1
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		go-fish: Go Fish 1.2.3-beta-1.16.5
		goldenhoppers: Golden Hoppers 1.0.2
		golemsgalore: Golems Galore 0.2.1+mc.1.16.5
		goml: Get Off My Lawn 1.3.4-beta
		graveyard: The Graveyard 1.1
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 2.0.4
		hctm-base: HCTM Base 3.5.1
		healthoverlay: Health Overlay 4.0.1
		ignis-fatuus: Ignis Fatuus 1.1.3
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		improved-stations: Improved Stations 2.0.3
		indium: Indium 1.0.0+mc1.16.5
		indrev: Industrial Revolution 1.9.18-BETA
		inmis: Inmis 2.2.1-1.16.5
		inventoryhud: Inventory HUD + 3.4.1
		inventorysorter: Inventory Sorter 1.7.9-1.16
		iris: Iris 1.2.4-build.36
		iron-jetpacks: Iron Jetpacks 0.3.1
		itemfilters: Item Filters 1605.2.5-build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		json-model-extensions: JSON Model Extensions 1.22.185
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.7-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1605.3.19-build.289
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.7
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.2.1
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		library_of_exile: Library of Exile 1.0.14
		libstructure: LibStructure 1.5
		lifts: Lifts 1.1.1-BETA
		lightoverlay: Light Overlay 5.8.1
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.6
		magna: Magna 1.5.3-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		megane: megane 4.1.4
		megane-applied-energistics-2: megane-applied-energistics-2 4.1.4+8.3.0-alpha.1
		megane-base: megane-base 4.1.4
		megane-fabric-furnaces: megane-fabric-furnaces 4.1.4+1.3.3-1.16.4
		megane-fast-transfer-lib: megane-fast-transfer-lib 4.1.4+0.3.1
		megane-industrial-revolution: megane-industrial-revolution 4.1.4+1.8.13-BETA
		megane-kibe: megane-kibe 4.1.4+1.6.6-BETA
		megane-lib-block-attributes: megane-lib-block-attributes 4.1.4+0.8.7
		megane-modern-industrialization-4: megane-modern-industrialization-4 4.1.4+0.4.0-alpha.11
		megane-runtime: megane-runtime 4.1.4
		megane-team-reborn-energy: megane-team-reborn-energy 4.1.4+0.1.0
		megane-tech-reborn: megane-tech-reborn 4.1.4+3.8.2-build.220
		megane-vanilla: megane-vanilla 4.1.4+1.16.5
		minecraft: Minecraft 1.16.5
		minershorizon: Miner's Horizon 1.6.2-1.16.5
		mixintrace: MixinTrace 1.0.0
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.5
		mocolors: Mo' Colors 1.1.2
		modern_industrialization: Modern Industrialization 0.4.0-alpha.11
		modmenu: Mod Menu 1.16.22
		more_tooltips: MoreTooltips 1.0.1
		morevillagers-fabric: MoreVillagersFabric 1.4.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.16.5
		mousetweaks: Mouse Tweaks 2.22
		mtmechs: Magitek Mechs 1.0.4
		multi_item_lib: Multi Item Lib 1.2.0
		myron: Myron 1.6.0
		mysticalagriculture: Mystical Agriculture: Refabricated 1.1.7
		mythic-mounts: Mythic Mounts 1.16.5-4.0
		netherite_plus: Netherite Plus Mod 1.4.3-1.16.5
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.10
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.0.1
		notes: Notes 1.0.4
		nourish: Nourish 1.3.2
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_scala-lang_scala-library: scala-library 2.13.6
		org_scala-lang_scala3-library_3: scala3-library_3 3.0.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		oro_config: OroArmor Config 2.0.0
		owo: OwO 0.1
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-53-FABRIC
		phosphor: Phosphor 0.8.0
		plasmo_voice: Plasmo Voice 1.2.11
		platforms: Platforms 1.0.1
		playerabilitylib: Pal 1.2.2
		pling: Pling 1.3.0
		promenade: Promenade 2.0
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industrial Quarry Mod 0.5.4
		quickshulker: Quick Shulker 1.1.14-1.16
		ratsmischief: Rat's Mischief 1.1.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.3+build.136
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		reroll: Reroll 1.2.1-1.16.5
		respawnablepets: Respawnable Pets 1.16.5-2
		rhino: Rhino 1605.1.5-build.75
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		rswires: RSWires 4.10.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 1.0.2
		sandwichable: Sandwichable 1.2-rc4+1.16
		secretrooms: Secret Rooms 0.9.5+1.16.5
		shetiphiancore: ShetiPhianCore 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 2.3.8+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		simplexterrain: Simplex Terrain 0.7.2
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		slotlock: SlotLock 1.0.3-BETA
		smootherbedrock: Smoother Bedrock 1.0.3
		sodium: Sodium 0.2.0+build.4
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		special-circumstances: Special Circumstances 1.8.221
		spruceui: SpruceUI 2.1.4+1.16
		stacc: Stacc 1.0.1
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		structurized: Structurized 1.2.0-1.16.5
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.5.2+mc.1.16.5
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.4+build.236
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.16
		terrestria: Terrestria 2.2.0
		tis3d: TIS-3D MC1.16.5-Fabric-1.6.2.35
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		toolstats: Tool Stats 1.0.1
		tooltipfix: ToolTip Fix 1.0.2-1.16
		totemmod: Wither Totems Mod 0.3.2
		trade: Trade 1.1.3
		trapexpansion: Trap Expansion 1.3.2
		travelersbackpack: Traveler's Backpack 1.16.5-5.4.0
		traverse: Traverse 3.3.3
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.3
		untitledduckmod: Untitled Duck Mod 0.2.2
		vanilla-hammers: Vanilla Hammers 3.0.3-1.16.5
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waystones: Waystones 2.0.1
		winged: Winged Mod 1.16.5-2.1.4
		wirelessnetworks: Wireless Networks 1.0.3
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wthit: wthit 2.10.11
		xlpackets: XLPackets 1.1
		yigd: You're in Grave Danger 1.0.3
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.12.12-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```
</details>

**Comment by thehaffk** [comment]
i definitely hate NullPointerException

**Comment by apehum** [comment]
Can you provide corrupted config.json?

**Comment by howkawgew** [comment]
Судя по скрину у тебя русский язык на компьютере, так что дальнейшее обсуждение можешь продолжать на русском

**Comment by Bizzonium** [comment]
> Can you provide corrupted config.json?

Sorry, forgot about the issue. Seems like it only happens on 1.18.2 1.2.13. I was using All of Fabric 5 1.2.2 modpack.
On MC 1.18.1 1.2.13 everything is fine
```json
{
  "servers": {
    "xxx.xxx.xxx.xxx": {
      "distance": 16,
      "priorityDistance": 48
    }
  },
  "playerVolumes": {},
  "whitelist": false,
  "voiceVolume": 1.0,
  "priorityVolume": 1.0,
  "occlusion": false,
  "speakerMuted": false,
  "showIcons": 0,
  "micIconPosition": "BOTTOM_CENTER",
  "voiceActivation": false,
  "voiceActivationThreshold": -30.0,
  "microphoneAmplification": 1.0,
  "rnNoise": false,
  "microphoneMuted": false,
  "javaxCapture": false,
  "hrtf": false,
  "directionalSources": false,
  "directionalSourcesAngle": 145,
  "compressor": true,
  "compressorThreshold": -10,
  "limiterThreshold": -6,
  "visualizeDistance": true,
  "keyBindings": {
    "pushToTalk": [
      {
        "type": "KEYSYM",
        "code": 342
      }
    ],
    "priorityPushToTalk": [],
    "muteMicrophone": [
      {
        "type": "KEYSYM",
        "code": 77
      }
    ],
    "muteChat": [],
    "action": [
      {
        "type": "MOUSE",
        "code": 1
      }
    ],
    "increaseDistance": [],
    "decreaseDistance": [],
    "occlusion": []
  },
  "showPriorityVolume": true,
  "micReverb": true,
  "micReverbVolume": 1.0
}
```

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
