### ISSUE TITLE
[Fabric] Muting someone crashes the server with NoClassDefFoundError

### ISSUE THREAD

**Issue by MrRubberDucky** [plasmoapp/plasmo-voice#220]
Aside from that, it works fine so not sure what's up and what's at fault here so any help would be appreciated

```[15:58:48] [Server thread/INFO]: OG_MrRubberDucky[/127.0.0.1:59347] logged in with entity id 44 at (772.9748520681616, 71.0, 44.11907513394884)
[15:58:48] [Server thread/INFO]: OG_MrRubberDucky joined the game
[15:58:57] [Server thread/INFO]: §6[Plasmo Voice]§7 Muted OG_MrRubberDucky for 1 sec. Reason: test
[15:58:57] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_4227
	at su.plo.voice.client.sound.openal.CustomSoundEngine.<init>(CustomSoundEngine.java:57) ~[plasmovoice-fabric-1.18-1.2.16.jar:?]
	at su.plo.voice.client.VoiceClient.<clinit>(VoiceClient.java:44) ~[plasmovoice-fabric-1.18-1.2.16.jar:?]
	at su.plo.voice.server.commands.VoiceMute.mute(VoiceMute.java:183) ~[plasmovoice-fabric-1.18-1.2.16.jar:?]
	at su.plo.voice.server.commands.VoiceMute.lambda$register$8(VoiceMute.java:82) ~[plasmovoice-fabric-1.18-1.2.16.jar:?]
	at java.util.Collections$SingletonSet.forEach(Collections.java:4905) ~[?:?]
	at su.plo.voice.server.commands.VoiceMute.lambda$register$9(VoiceMute.java:81) ~[plasmovoice-fabric-1.18-1.2.16.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.redirect$zzk000$performCommand(class_2170.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:264) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_13941(class_3176.java:338) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4227
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 15 more
```
	
Mods: Fabric API 50.0, Plasmo Voice 1.2.16, LuckPerms 5.4.14 (also happens on latest Fabric Loader, LP and Fabric API - this is on a clean instance i had lying around), forgot to say this is in 1.18.2

**Comment by MrRubberDucky** [comment]
Hey, thanks for fixing it! :D
