### ISSUE TITLE
Opus encoding crashing on Gentoo Linux

### ISSUE THREAD

**Issue by ghost** [plasmoapp/plasmo-voice#227]
When playing on Gentoo Linux, the Opus encoder crashes as soon as I try to talk.

```java
[16:48:50] [Input Device Recorder/ERROR]: Uncaught exception in thread "Input Device Recorder"
java.lang.RuntimeException: Failed to encode audio data
	at su.plo.voice.client.sound.opus.OpusEncoder.encode(OpusEncoder.java:47) ~[plasmovoice-fabric-1.19-1.2.17.jar:?]
	at su.plo.voice.client.sound.Recorder.sendPacket(Recorder.java:386) ~[plasmovoice-fabric-1.19-1.2.17.jar:?]
	at su.plo.voice.client.sound.Recorder.voiceActivation(Recorder.java:278) ~[plasmovoice-fabric-1.19-1.2.17.jar:?]
	at su.plo.voice.client.sound.Recorder.run(Recorder.java:220) ~[plasmovoice-fabric-1.19-1.2.17.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
