### ISSUE TITLE
[WARNING] Error loading plugin PlasmoVoice

### ISSUE THREAD

**Issue by DENPOY** [plasmoapp/plasmo-voice#235]
00:08:59 [WARNING] Error loading plugin PlasmoVoice
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClas
s(ClassLoader.java:519)
    ... 13 more

**Comment by bottleofench** [comment]
What version of the plugin? Perhaps you should use [this version](https://github.com/plasmoapp/plasmo-voice/releases/tag/1.0.12-test). Are you trying to run the plugin on BungeeCord? Maybe you configured/installed something wrong. Double-check everything and do as described [here](https://github.com/plasmoapp/plasmo-voice/wiki/How-to-Setup-Proxy).

**Comment by Toldoven** [comment]
We no longer support 1xx version of the mod because version 2xx is coming out soon.

You can start a new issue if it is still relevant in 2xx.
