### ISSUE TITLE
Постоянные проблемы с соединением 

### ISSUE THREAD

**Issue by WandererRT** [plasmoapp/plasmo-voice#27]
Установил плагин на сервер, версия 1.16.5, плагин постоянно перестаёт работать (микрофон блокируется) из-за проблем с соединением, которые появляются либо со случайно частотой, либо раз в 6-7 секунд. Консоль выдает такую ошибку:
[Thread-9/WARN]: java.io.IOException: Operation not permitted (sendto failed)
[Thread-9/WARN]: at java.net.PlainDatagramSocketImpl.send(Native Method)
[Thread-9/WARN]: at java.net.DatagramSocket.send(DatagramSocket.java:693)
[Thread-9/WARN]: at su.plo.voice.socket.SocketServerUDP.sendTo(SocketServerUDP.java:66)
[Thread-9/WARN]: at su.plo.voice.socket.SocketServerUDPQueue.run(SocketServerUDPQueue.java:52)`

**Comment by WandererRT** [comment]
Проблема решилась сменой порта
