### ISSUE TITLE
crash on startup on bungeecord proxy

### ISSUE THREAD

**Issue by catAngent** [plasmoapp/plasmo-voice#299]
plasmovoice crashes immediately after startup.

using latest bungeecord version and plasmovoice-bungeecord version 2.0.2

12:18:05 [WARNING] Error loading plugin PlasmoVoice
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:342)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at su.plo.voice.proxy.BaseVoiceProxy.<init>(BaseVoiceProxy.java:78)
	at su.plo.voice.bungee.BungeeVoiceProxy.<init>(BungeeVoiceProxy.kt:19)
	at su.plo.voice.bungee.BungeeVoiceLoader.<init>(BungeeVoiceLoader.kt:8)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more

**Comment by Apehum** [comment]
Use prerelease: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.3

**Comment by Apehum** [comment]
https://modrinth.com/plugin/plasmo-voice/version/BungeeCord-2.0.3
