### ISSUE TITLE
Не работает плагин после второго запуска

### ISSUE THREAD

**Issue by itzJOHv** [plasmoapp/plasmo-voice#31]
На первом запуске все работало отлично, но после рестарта плагин перестал работать и начал говорить при входе что он не может открыть порт UDP.
![image](https://user-images.githubusercontent.com/68508885/116982940-204da080-acd2-11eb-87b3-ea96e28d3b6a.png)
![image](https://user-images.githubusercontent.com/68508885/116982986-32c7da00-acd2-11eb-9e4c-5d0d6f97a463.png)

**Comment by howkawgew** [comment]
Во первых проверьте правильно ли указан ip в конфиге, точно ли там стоит 25370, в крайнем случае попробуйте сменить порт и там и там. Еще возможно PlasmoVoice логирует какое-то исключение в консоль сервера, проверьте пожалуйста

**Comment by itzJOHv** [comment]
еще откопал ошибочку при запуске
```
[23:58:21 WARN]: java.net.BindException: Cannot assign requested address (Bind failed)
[23:58:21 WARN]:        at java.net.PlainDatagramSocketImpl.bind0(Native Method)
[23:58:21 WARN]:        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
[23:58:21 WARN]:        at java.net.DatagramSocket.bind(DatagramSocket.java:392)
[23:58:21 WARN]:        at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
[23:58:21 WARN]:        at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:78)
[23:58:21 INFO]: [PlasmoVoice] Failed to bind socket. Check if port 25730 UDP is open
```

**Comment by howkawgew** [comment]
Склоняюсь к тому что проблема на стороне хостинга. Это же майнкрафт хостинг?

**Comment by itzJOHv** [comment]
Селфхостинг, проблема исправилась заменив IP на `0.0.0.0` (локал) с публичного
