### ISSUE TITLE
Plasmo Voice is not installed on this server

### ISSUE THREAD

**Issue by MaxOne037** [plasmoapp/plasmo-voice#313]
I downloaded the Plasma 2.0.4 Voice Server from the official website for my Crane server. Plasma Voice forge 1.19.3 is installed on the client. I get an error: Plasmo Voice is not installed on this server

**Comment by MaxOne037** [comment]
[PlasmoVoice] Enabling PlasmoVoice v2.0.4
[15:43:38] [Server thread/ERROR]: Error occurred while enabling PlasmoVoice v2.0.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandMap org.bukkit.Server.getCommandMap()'
at su.plo.lib.paper.command.PaperCommandManager.registerCommands(PaperCommandManager.kt:21) ~[?:?]
at su.plo.voice.paper.PaperVoiceServer.onInitialize(PaperVoiceServer.kt:32) ~[?:?]
at su.plo.voice.paper.PaperVoiceLoader.onEnable(PaperVoiceLoader.kt:10) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3630-Spigot-d90018e-ae8f5fc]
at java.lang.Thread.run(Unknown Source) ~[?:?]
[15:43:38] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[15:43:38] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[15:43:38] [Server thread/INFO]: [nLogin] Enabling nLogin v10.1.14
[15:43:38] [Server thread/INFO]: [nLogin] Successful plugin core start (took 0.50s)

**Comment by apehum** [comment]
Try with latest versions, if issue persists, reopen the issue and send logs
