### ISSUE TITLE
[Error] plugin generates a exception, player can't connect to UDP server

### ISSUE THREAD

**Issue by rm20killer** [plasmoapp/plasmo-voice#316]
Client - plasmovoice 2.0.3  https://mclo.gs/oPCSHys

server - PlasmoVoice v2.0.4 on paper 1.19.2

Server log
```
[01:52:38] [Server thread/WARN]: [PlasmoVoice] Plugin PlasmoVoice v2.0.4 generated an exception whilst handling plugin message
java.lang.IllegalStateException: Player is not connected to UDP server
	at su.plo.voice.server.player.VoiceServerPlayerEntity.createPlayerInfo(VoiceServerPlayerEntity.java:46) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.server.connection.VoiceTcpServerConnectionManager.broadcastPlayerInfoUpdate(VoiceTcpServerConnectionManager.java:156) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.server.connection.PlayerChannelHandler.handle(PlayerChannelHandler.java:87) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.proto.packets.tcp.serverbound.PlayerStatePacket.handle(PlayerStatePacket.java:37) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.proto.packets.tcp.serverbound.PlayerStatePacket.handle(PlayerStatePacket.java:13) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.server.connection.PlayerChannelHandler.handlePacket(PlayerChannelHandler.java:47) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at su.plo.voice.paper.connection.PaperServerChannelHandler.onPluginMessageReceived$lambda-1(PaperServerChannelHandler.kt:36) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at su.plo.voice.paper.connection.PaperServerChannelHandler.onPluginMessageReceived(PaperServerChannelHandler.kt:29) ~[PlasmoVoice-Paper-2.0.4.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3686) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by apehum** [comment]
Should be fixed in latest versions
