### ISSUE TITLE
[BUG]Stuck in save world screen when exiting single player world.

### ISSUE THREAD

**Issue by surfishs** [plasmoapp/plasmo-voice#341]
Stuck in save world screen when exiting single player world.
How to reproduce: Quit and play
The game is completely stuck and cannot be exited using Alt+F4, only the mission process can be ended.
Normally it doesn't give any error reporting information because the game is frozen straight away, but this is the error reporting feedback I got by chance.
- [18:36:43] [Server thread/ERROR]: Uncaught exception in server thread
java.util.concurrent.RejectedExecutionException: DefaultDispatcher was terminated
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch(CoroutineScheduler.kt:391) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default(CoroutineScheduler.kt:382) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.SchedulerCoroutineDispatcher.dispatch(Dispatcher.kt:97) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.ustats.UStats.startJob(UStats.kt:54) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.ustats.UStats.<init>(UStats.kt:42) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.server.ModVoiceServer.onInitialize(ModVoiceServer.java:94) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.server.ModVoiceServer.lambda$onInitialize$0(ModVoiceServer.java:142) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b82-592633ca710f96fc.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zol000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2342) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	Suppressed: su.plo.voice.libs.kotlinx.coroutines.DiagnosticCoroutineContextException
[18:36:43] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.RejectedExecutionException: DefaultDispatcher was terminated
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch(CoroutineScheduler.kt:391) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default(CoroutineScheduler.kt:382) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.scheduling.SchedulerCoroutineDispatcher.dispatch(Dispatcher.kt:97) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.libs.kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.ustats.UStats.startJob(UStats.kt:54) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.ustats.UStats.<init>(UStats.kt:42) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.server.ModVoiceServer.onInitialize(ModVoiceServer.java:94) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at su.plo.voice.server.ModVoiceServer.lambda$onInitialize$0(ModVoiceServer.java:142) ~[plasmovoice-fabric-1.20-2.0.5.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b82-592633ca710f96fc.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zol000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2342) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	Suppressed: su.plo.voice.libs.kotlinx.coroutines.DiagnosticCoroutineContextException

**Comment by apehum** [comment]
Try prerelease:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6

**Comment by apehum** [comment]
Fixed in 2.0.6:
https://modrinth.com/plugin/plasmo-voice/versions
