### ISSUE TITLE
Can't change overlay position

### ISSUE THREAD

**Issue by ItsukaHiro** [plasmoapp/plasmo-voice#343]
Just like the title. If I try to change, it will, immediately crash the game.

Log:
```[16:52:31] [Render thread/ERROR]: ########## GL ERROR ##########
[16:52:31] [Render thread/ERROR]: @ Render
[16:52:31] [Render thread/ERROR]: 65540: Invalid scancode -1
[16:52:38] [Server thread/INFO]: Saving and pausing game...
[16:52:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[16:52:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[16:52:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[16:52:51] [Server thread/INFO]: UDP server is stopped
[16:52:51] [Server thread/INFO]: Stopping server
[16:52:51] [Server thread/INFO]: Saving players
[16:52:51] [Server thread/INFO]: Saving worlds
[16:52:51] [Netty Local Client IO #0/INFO]: Disconnecting from /127.0.0.1:55406 with reason DISCONNECT
[16:52:51] [Netty Local Client IO #0/INFO]: Device OpenAL Soft on Microphone Array (Realtek Audio) closed
[16:52:51] [Voice Audio Capture/INFO]: Device OpenAL Soft on Microphone Array (Realtek Audio) closed
[16:52:51] [Al Output Device OpenAL Soft on Speakers/Headphones (Realtek Audio)/INFO]: Device OpenAL Soft on Speakers/Headphones (Realtek Audio) closed
[16:52:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[16:52:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[16:52:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[16:52:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[16:52:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:52:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:52:52] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[16:52:52] [Render thread/INFO]: Stopping worker threads
[16:52:53] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:545) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldError: width
	at su.plo.voice.client.gui.settings.tab.ActivationIconPositionScreen.init(ActivationIconPositionScreen.java:29) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.initScreen(ScreenWrapper.java:77) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.universal.UScreen.method_25426(UScreen.kt:70) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1079) ~[client-intermediary.jar:?]
	at su.plo.voice.universal.UScreen$Companion.displayScreen(UScreen.kt:389) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.universal.UScreen.displayScreen(UScreen.kt) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.lambda$openScreen$1(ScreenWrapper.java:38) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.openScreen(ScreenWrapper.java:38) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.client.gui.settings.tab.OverlayTabWidget.lambda$createActivationIconPosition$4(OverlayTabWidget.java:186) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.components.Button.onPress(Button.java:36) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.components.AbstractButton.onClick(AbstractButton.java:22) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.widget.GuiAbstractWidget.mouseClicked(GuiAbstractWidget.java:105) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.client.gui.settings.tab.TabWidget.mouseClicked(TabWidget.java:106) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.client.gui.settings.VoiceSettingsScreen.mouseClicked(VoiceSettingsScreen.java:196) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.onMouseClicked(ScreenWrapper.java:112) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at su.plo.voice.universal.UScreen.method_25402(UScreen.kt:111) ~[plasmovoice-fabric-1.19.4-2.0.5.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:540) ~[client-intermediary.jar:?]
	... 19 more
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
Time: 2023-06-16 16:52:53
Description: mouseClicked event handler
java.lang.NoSuchFieldError: width
	at su.plo.voice.client.gui.settings.tab.ActivationIconPositionScreen.init(ActivationIconPositionScreen.java:29)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.initScreen(ScreenWrapper.java:77)
	at su.plo.voice.universal.UScreen.method_25426(UScreen.kt:70)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at su.plo.voice.universal.UScreen$Companion.displayScreen(UScreen.kt:389)
	at su.plo.voice.universal.UScreen.displayScreen(UScreen.kt)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.lambda$openScreen$1(ScreenWrapper.java:38)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.openScreen(ScreenWrapper.java:38)
	at su.plo.voice.client.gui.settings.tab.OverlayTabWidget.lambda$createActivationIconPosition$4(OverlayTabWidget.java:186)
	at su.plo.lib.mod.client.gui.components.Button.onPress(Button.java:36)
	at su.plo.lib.mod.client.gui.components.AbstractButton.onClick(AbstractButton.java:22)
	at su.plo.lib.mod.client.gui.widget.GuiAbstractWidget.mouseClicked(GuiAbstractWidget.java:105)
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36)
	at su.plo.voice.client.gui.settings.tab.TabWidget.mouseClicked(TabWidget.java:106)
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36)
	at su.plo.voice.client.gui.settings.VoiceSettingsScreen.mouseClicked(VoiceSettingsScreen.java:196)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.onMouseClicked(ScreenWrapper.java:112)
	at su.plo.voice.universal.UScreen.method_25402(UScreen.kt:111)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:216)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at su.plo.voice.client.gui.settings.tab.ActivationIconPositionScreen.init(ActivationIconPositionScreen.java:29)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.initScreen(ScreenWrapper.java:77)
	at su.plo.voice.universal.UScreen.method_25426(UScreen.kt:70)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at su.plo.voice.universal.UScreen$Companion.displayScreen(UScreen.kt:389)
	at su.plo.voice.universal.UScreen.displayScreen(UScreen.kt)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.lambda$openScreen$1(ScreenWrapper.java:38)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.openScreen(ScreenWrapper.java:38)
	at su.plo.voice.client.gui.settings.tab.OverlayTabWidget.lambda$createActivationIconPosition$4(OverlayTabWidget.java:186)
	at su.plo.lib.mod.client.gui.components.Button.onPress(Button.java:36)
	at su.plo.lib.mod.client.gui.components.AbstractButton.onClick(AbstractButton.java:22)
	at su.plo.lib.mod.client.gui.widget.GuiAbstractWidget.mouseClicked(GuiAbstractWidget.java:105)
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36)
	at su.plo.voice.client.gui.settings.tab.TabWidget.mouseClicked(TabWidget.java:106)
	at su.plo.lib.mod.client.gui.screen.GuiScreenListener.mouseClicked(GuiScreenListener.java:36)
	at su.plo.voice.client.gui.settings.VoiceSettingsScreen.mouseClicked(VoiceSettingsScreen.java:196)
	at su.plo.lib.mod.client.gui.screen.ScreenWrapper.onMouseClicked(ScreenWrapper.java:112)
	at su.plo.voice.universal.UScreen.method_25402(UScreen.kt:111)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:216)
-- Affected screen --
Details:
	Screen name: su.plo.lib.mod.client.gui.screen.ScreenWrapper
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:216)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Affected level --
Details:
	All players: 1 total; [class_746['ItsukHiro'/1, l='ClientLevel', x=-14.48, y=0.00, z=-22.95]]
	Chunk stats: 1024, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 299 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 916532032 bytes (874 MiB) / 1698693120 bytes (1620 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 24564.98
	Virtual memory used (MB): 14103.85
	Swap memory total (MB): 16492.05
	Swap memory used (MB): 4690.47
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		debugify: Debugify 1.19.4+2.2
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fabric-api: Fabric API 0.83.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.18+10ce000ff4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.12+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.3+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.8+10ce000ff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.30+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.34+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.42+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.6+10ce000ff4
			fabric-particles-v1: Fabric Particles (v1) 1.0.26+10ce000ff4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.3.1+10ce000ff4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+10ce000ff4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.5+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.1+10ce000ff4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 5.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.1.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.3
		moreculling: More Culling 1.19.4-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		plasmovoice: Plasmo Voice 2.0.5
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			javax_inject_javax_inject: javax.inject 1
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.1+fabric.ae22326
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.1+1.19.4
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
			yet_another_config_lib: YetAnotherConfigLib 2.5.1+1.19.4
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 620 GL version 3.2.0 - Build 31.0.101.2115, Intel
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['ItsukHiro'/1, l='ServerLevel[New World]', x=-14.48, y=0.00, z=-22.95]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
#@!@# Game crashed! Crash report saved to: #@!@# C:\PrismLauncher\instances\Main Instance\.minecraft\crash-reports\crash-2023-06-16_16.52.53-client.txt
Process exited with code -1.
``

**Comment by apehum** [comment]
Should be fixed in prerelease:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6

**Comment by ItsukaHiro** [comment]
> Should be fixed in prerelease:
> https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6

Yah it's actually fix this problem, thanks.
