### ISSUE TITLE
Ошибка, плагин не работает

### ISSUE THREAD

**Issue by foxya27** [plasmoapp/plasmo-voice#344]
09:50:56] [Server thread/INFO]: [PlasmoVoice] Disabling PlasmoVoice v2.0.5
[09:50:56] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling PlasmoVoice v2.0.5 (Is it up to date?)
java.lang.IllegalArgumentException: Plugin must be enabled to send messages
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:538) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:2148) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at su.plo.lib.paper.entity.PaperServerPlayer.sendPacket(PaperServerPlayer.kt:58) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.player.VoiceServerPlayerEntity.sendPacket(VoiceServerPlayerEntity.java:34) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.connection.VoiceTcpServerConnectionManager.broadcast(VoiceTcpServerConnectionManager.java:39) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.api.server.connection.ConnectionManager.broadcast(ConnectionManager.java:23) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.socket.NettyUdpServerConnection.disconnect(NettyUdpServerConnection.java:94) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.connection.VoiceUdpServerConnectionManager.disconnect(VoiceUdpServerConnectionManager.java:126) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.connection.VoiceUdpServerConnectionManager.removeConnection(VoiceUdpServerConnectionManager.java:82) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783) ~[?:?]
	at su.plo.voice.server.connection.VoiceUdpServerConnectionManager.clearConnections(VoiceUdpServerConnectionManager.java:121) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.socket.NettyUdpServer.stop(NettyUdpServer.java:72) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.BaseVoiceServer.stopUdpServer(BaseVoiceServer.java:304) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.server.BaseVoiceServer.onShutdown(BaseVoiceServer.java:178) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.paper.PaperVoiceServer.onShutdown(PaperVoiceServer.kt:73) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at su.plo.voice.paper.PaperVoiceLoader.onDisable(PaperVoiceLoader.kt:14) ~[PlasmoVoice-Paper-2.0.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:507) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:956) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:846) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by apehum** [comment]
Загрузи полностью логи на mclo.gs и скинь сюда

**Comment by foxya27** [comment]
> Загрузи полностью логи на mclo.gs и скинь сюда

https://mclo.gs/9sHEdaA

**Comment by djohts** [comment]
тоже такое происходит при остановке сервера

**Comment by foxya27** [comment]
> тоже такое происходит при остановке сервера

Надеюсь пофиксят

**Comment by apehum** [comment]
Должно быть пофикшено в пререлизе:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.0.6
