### ISSUE TITLE
Crash on Android (PojavLauncher)

### ISSUE THREAD

**Issue by BlayzerQ** [plasmoapp/plasmo-voice#345]
When I try to start minecraft with Plasma Voice from the PojavLauncher and connect to server - game crashed.

Description: Unexpected error

java.lang.UnsatisfiedLinkError: dlopen failed: library "libm.so.6" not found: needed by /data/data/net.kdt.pojavlaunch.debug/cache/jna-109576275/jna5092727591492092318.tmp in namespace classloader-namespace
	at com.sun.jna.Native.open(Native Method) ~[jna-4.4.0.jar:4.4.0 (b0)] {}
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288) ~[jna-4.4.0.jar:4.4.0 (b0)] {re:classloading}
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427) ~[jna-4.4.0.jar:4.4.0 (b0)] {re:classloading}
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:369) ~[jna-4.4.0.jar:4.4.0 (b0)] {re:classloading}
	at tomp2p.opuswrapper.Opus.<clinit>(Opus.java:26) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.sound.opus.OpusEncoder.<init>(OpusEncoder.java:28) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.sound.Recorder.updateSampleRateSync(Recorder.java:100) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.sound.Recorder.updateSampleRate(Recorder.java:88) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.config.ServerSettings.update(ServerSettings.java:94) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.network.ClientNetworkHandler.handle(ClientNetworkHandler.java:77) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.client.network.ClientNetworkHandlerForge.handle(ClientNetworkHandlerForge.java:24) ~[plasmo_voice:?] {re:classloading}
	at su.plo.voice.VoiceForge.lambda$commonSetup$1(VoiceForge.java:43) ~[plasmo_voice:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.
post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_372-internal] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] 
[latestlog (10).txt](https://github.com/plasmoapp/plasmo-voice/files/11780185/latestlog.10.txt)

**Comment by BlayzerQ** [comment]
If there is at least a direction to solve the problem, please give information. Perhaps need to recompile the opus dependency for a different architecture?

**Comment by thehaffk** [comment]
PojavLauncher is not supported

**Comment by apehum** [comment]
1.x.x is not supported
