### ISSUE TITLE
Баг Placeholder

### ISSUE THREAD

**Issue by foxya27** [plasmoapp/plasmo-voice#349]
https://mclo.gs/YgDQLBv

Делал как в гайде из вики https://github.com/plasmoapp/plasmo-voice/wiki/PlaceholderAPI
 
Версия плазмо 2.0.5

**Comment by foxya27** [comment]
?

**Comment by foxya27** [comment]
14:59:10 WARN]: [PlasmoVoice] Failed to fire an event:

[14:59:10 WARN]: java.lang.reflect.InvocationTargetException

[14:59:10 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)

[14:59:10 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:577)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.event.VoiceEventBus.lambda$register$1(VoiceEventBus.java:106)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.event.VoiceEventBus.call(VoiceEventBus.java:51)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.server.connection.PlayerChannelHandler.handle(PlayerChannelHandler.java:112)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.proto.packets.tcp.serverbound.PlayerAudioEndPacket.handle(PlayerAudioEndPacket.java:45)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.proto.packets.tcp.serverbound.PlayerAudioEndPacket.handle(PlayerAudioEndPacket.java:17)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.server.connection.PlayerChannelHandler.handlePacket(PlayerChannelHandler.java:48)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.paper.connection.PaperServerChannelHandler.onPluginMessageReceived$lambda-1(PaperServerChannelHandler.kt:36)

[14:59:10 WARN]: at java.base/java.util.Optional.ifPresent(Optional.java:178)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.paper.connection.PaperServerChannelHandler.onPluginMessageReceived(PaperServerChannelHandler.kt:29)

[14:59:10 WARN]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)

[14:59:10 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3667)

[14:59:10 WARN]: at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)

[14:59:10 WARN]: at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)

[14:59:10 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)

[14:59:10 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)

[14:59:10 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)

[14:59:10 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)

[14:59:10 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)

[14:59:10 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1314)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)

[14:59:10 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)

[14:59:10 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

[14:59:10 WARN]: Caused by: java.lang.IllegalArgumentException: Cannot measure distance between worlds

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.lib.api.server.world.ServerPos3d.distanceSquared(ServerPos3d.java:43)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.server.audio.source.VoiceServerPositionalSource.sendPacket(VoiceServerPositionalSource.kt:77)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.api.server.audio.capture.ProximityServerActivationHelper.sendAudioEndPacket(ProximityServerActivationHelper.kt:91)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.api.server.audio.capture.ProximityServerActivationHelper.onActivationEnd(ProximityServerActivationHelper.kt:76)

[14:59:10 WARN]: at PlasmoVoice-Paper-2.0.6.jar//su.plo.voice.server.audio.capture.VoiceServerActivationManager.onPlayerSpeakEnd(VoiceServerActivationManager.kt:152)

[14:59:10 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

[14:59:10 WARN]: ... 28 more

**Comment by foxya27** [comment]
Последняя версия вызывает такую ошибку

**Comment by apehum** [comment]
Проблема осталась? Если да, то скинь полностью логи
