### ISSUE TITLE
Plasmo voice just didn't work and spam console with errors

### ISSUE THREAD

**Issue by NhProGamer** [plasmoapp/plasmo-voice#354]
I have one lobby with a velocity proxy
i can speak 6 seconds and after my client is disconnected, only when i talk i have these errors in the console

```
[16:17:36 INFO] [PlasmoVoice]: Packet PacketUdp(secret=0ba071ce-25f1-437c-95a7-7c7a323e19cf, timestamp=1688221056310) was received from remote server: /172.18.0.1:25510; connection remote server: /172.17.0.1:25510
[16:17:36 ERROR]: java.lang.ClassCastException: class su.plo.voice.proxy.socket.NettyUdpProxyConnection cannot be cast to class su.plo.voice.proto.packets.udp.clientbound.ClientPacketUdpHandler (su.plo.voice.proxy.socket.NettyUdpProxyConnection and su.plo.voice.proto.packets.udp.clientbound.ClientPacketUdpHandler are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @14f3c6fc)
[16:17:36 ERROR]:       at su.plo.voice.proto.packets.udp.clientbound.SelfAudioInfoPacket.handle(SelfAudioInfoPacket.java:18)
[16:17:36 ERROR]:       at su.plo.voice.proxy.socket.NettyUdpProxyConnection.handlePacket(NettyUdpProxyConnection.java:59)
[16:17:36 ERROR]:       at su.plo.voice.proxy.socket.NettyPacketHandler.sendPacket(NettyPacketHandler.java:110)
[16:17:36 ERROR]:       at su.plo.voice.proxy.socket.NettyPacketHandler.lambda$channelRead0$0(NettyPacketHandler.java:40)
[16:17:36 ERROR]:       at java.base/java.util.Optional.map(Optional.java:260)
[16:17:36 ERROR]:       at su.plo.voice.proxy.socket.NettyPacketHandler.channelRead0(NettyPacketHandler.java:40)
[16:17:36 ERROR]:       at su.plo.voice.proxy.socket.NettyPacketHandler.channelRead0(NettyPacketHandler.java:28)
[16:17:36 ERROR]:       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[16:17:36 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[16:17:36 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[16:17:36 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
[16:17:36 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:17:36 ERROR]:       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
[16:17:36 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:17:36 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:17:36 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:17:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by yungnickyoung** [comment]
@NhProGamer Can you share how you fixed this? Currently experiencing the same issue.
