### ISSUE TITLE
Микрофон всегда скидывается при попытке захвата

### ISSUE THREAD

**Issue by StreamVersus** [plasmoapp/plasmo-voice#366]
`[12:21:26] [pool-10-thread-1/ERROR]: Failed to open input device
su.plo.voice.api.client.audio.device.DeviceException: Failed to open javax device
	at su.plo.voice.client.audio.device.JavaxInputDevice.open(JavaxInputDevice.java:96) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.JavaxInputDevice.<init>(JavaxInputDevice.java:24) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.JavaxInputDeviceFactory.openDevice(JavaxInputDeviceFactory.java:34) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.VoiceDeviceManager.openJavaxInputDevice(VoiceDeviceManager.java:299) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.VoiceDeviceManager.openInputDevice(VoiceDeviceManager.java:162) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.VoiceDeviceManager.tickJob(VoiceDeviceManager.java:262) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at su.plo.voice.client.audio.device.VoiceDeviceManager.lambda$startJob$4(VoiceDeviceManager.java:209) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:484) ~[?:?]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:115) ~[?:?]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:142) ~[?:?]
	at su.plo.voice.client.audio.device.JavaxInputDevice.open(JavaxInputDevice.java:94) ~[plasmovoice-fabric-1.20.1-2.0.6.jar:?]
	... 12 more`

**Comment by apehum** [comment]
Какая OS?
Микрофон работает в других приложениях?

**Comment by StreamVersus** [comment]
Windows 10
Да, работает в дискорде
Java и стандартная(из обычного лаунчера), и adoptium последний LTS тестился

**Comment by apehum** [comment]
Если выключить дискорд, то микрофон все равно не работает?

**Comment by StreamVersus** [comment]
Нет, все равно не захватывает микрофон, и сбрасывает настройку

**Comment by apehum** [comment]
Скинь полностью лог

**Comment by StreamVersus** [comment]
https://pastebin.com/fgGGBAGf
извиняюсь за игнор

**Comment by thehaffk** [comment]
В issue не было никакой активности год
