### ISSUE TITLE
IP address not updates after recreate minecraft's server docker container

### ISSUE THREAD

**Issue by andreypfau** [plasmoapp/plasmo-voice#376]
I have all minecraft servers in docker containers.

My velocity plasmovoice/config.yml
```yaml
[servers]
vanilla = "pfaumc-vanilla-1:25565"

[host]
ip = "0.0.0.0"
port = 25565
```

After recreating of docker container named as `pfaumc-vanilla-1` internal IP address of container changes, but velocity plasmovoice still try to connect to old IP

# How to fix?
Change one-time resolving of IP address, need to resolve IP server dynamicly (maybe with cache with 1 minute timeout)

**Comment by andreypfau** [comment]
https://github.com/plasmoapp/plasmo-voice/blob/120f5a8681a69cb85eb4a4c744aafa627ca1cd38/proxy/common/src/main/java/su/plo/voice/proxy/server/VoiceRemoteServerManager.java#L95

Here address resolves only on starting of velocity, and not updates later

**Comment by andreypfau** [comment]
Any updates?

**Comment by apehum** [comment]
Should be fixed in 2.1.0 by this commit ca6ce2e9d0e8ba33b3f59e6967d42be36bc8645f

Prerelease is available here:
https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT

**Comment by andreypfau** [comment]
> Should be fixed in 2.1.0 by this commit [ca6ce2e](https://github.com/plasmoapp/plasmo-voice/commit/ca6ce2e9d0e8ba33b3f59e6967d42be36bc8645f)
> 
> Prerelease is available here: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT

```
[13:14:48 ERROR]: Couldn't pass ProxyInitializeEvent to plasmovoice
2024-01-23T13:14:48.261984898Z java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
2024-01-23T13:14:48.261988013Z 	at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:251) ~[?:?]
2024-01-23T13:14:48.261990398Z 	at org.bstats.MetricsBase.<init>(MetricsBase.java:121) ~[?:?]
2024-01-23T13:14:48.261992903Z 	at org.bstats.velocity.Metrics.<init>(Metrics.java:84) ~[?:?]
2024-01-23T13:14:48.261995157Z 	at org.bstats.velocity.Metrics.<init>(Metrics.java:18) ~[?:?]
2024-01-23T13:14:48.261997421Z 	at org.bstats.velocity.Metrics$Factory.make(Metrics.java:49) ~[?:?]
2024-01-23T13:14:48.261999605Z 	at su.plo.voice.velocity.VelocityVoiceProxy.onProxyInitialization(VelocityVoiceProxy.kt:51) ~[?:?]
2024-01-23T13:14:48.262001749Z 	at su.plo.voice.velocity.Lmbda$3.execute(Unknown Source) ~[?:?]
2024-01-23T13:14:48.262003933Z 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-343.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
2024-01-23T13:14:48.262007079Z 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.3.0-SNAPSHOT-343.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
2024-01-23T13:14:48.262009463Z 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.3.0-SNAPSHOT-343.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
2024-01-23T13:14:48.262011818Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
2024-01-23T13:14:48.262013992Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
2024-01-23T13:14:48.262016126Z 	at java.lang.Thread.run(Thread.java:840) [?:?]
```
