### ISSUE TITLE
error on server

### ISSUE THREAD

**Issue by ghost** [plasmoapp/plasmo-voice#380]
[14:11:52] [Craft Scheduler Thread - 1/WARN]: [PlasmoVoice] Plugin PlasmoVoice v1.0.13 generated an exception while executing task 1909
 java.lang.NoSuchMethodError: su.plo.voice.common.packets.tcp.ConfigPacket.<init>(ILjava/util/List;IIIIZ)V
        at su.plo.voice.listeners.PluginChannelListener.lambda$onPluginMessageReceived$0(PluginChannelListener.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by apehum** [comment]
1.0.x is not supported
