### ISSUE TITLE
Bad memory leak

### ISSUE THREAD

**Issue by JerichoTorrent** [plasmoapp/plasmo-voice#413]
With plasmovoice -> horrible memory leak, all servers using it crash every 30 minutes or so. Memory keeps building up well over that which is allocated to the container, far past Xmx, then crashes due to OOM
Without plasmovoice -> server functions at optimal performance and memory is managed well
Guys, I don't really have any logs or anything to show for this one, but I can promise you plasmovoice was exclusively causing this memory leak. I was running plasmovoice-velocity on two proxy servers, and plasmovoice-paper on 4 backend servers. I also had plasmovoice-groups installed on the proxies. All servers on 1.21.
Please fix whatever is causing memory leaks this severe, or tell me what I can do differently to ensure this does not occur.

**Comment by thehaffk** [comment]
thousands of servers use plasmo voice and only you have reported that it is causing memory leak

please provide logs or some details like your server version, name, list of plugins and crashlogs or this issue will be ignored as not reproducible

**Comment by VOrlando520** [comment]
Can also say this is affecting me on Velocity 1.20.1 and my modded Fabric 1.20.1 server as well. Just had a crash last night after uploading and using it for a bit

`---- Minecraft Crash Report ----
// You're mean.

Time: 2024-10-17 05:16:20
Description: Exception in server tick loop

java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.base@17.0.7/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
`

**Comment by apehum** [comment]
Try using latest alpha version: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.1.
If that doesn't help, there is nothing I can do without analyzing a heap dump. Check out the second paragraph here: https://docs.pufferfish.host/general/why-is-my-ram-all-used/#what-is-a-memory-leak.
