### ISSUE TITLE
Cannot measure distance between worlds

### ISSUE THREAD

**Issue by foxya27** [plasmoapp/plasmo-voice#422]
[20:47:59 WARN]: [PlasmoVoice] Failed to fire an event:
[20:47:59 WARN]: java.lang.reflect.InvocationTargetException
[20:47:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[20:47:59 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.event.VoiceEventBus.lambda$register$1(VoiceEventBus.java:104)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.event.VoiceEventBus.fire(VoiceEventBus.java:49)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.connection.PlayerChannelHandler.handle(PlayerChannelHandler.java:122)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.proto.packets.tcp.serverbound.PlayerAudioEndPacket.handle(PlayerAudioEndPacket.java:45)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.proto.packets.tcp.serverbound.PlayerAudioEndPacket.handle(PlayerAudioEndPacket.java:17)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.connection.PlayerChannelHandler.handlePacket(PlayerChannelHandler.java:48)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.connection.ServerChannelHandler.lambda$receive$1(ServerChannelHandler.java:50)
[20:47:59 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.connection.ServerChannelHandler.receive(ServerChannelHandler.java:41)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.slib.spigot.channel.SpigotChannelManager.onPluginMessageReceived(SpigotChannelManager.kt:55)
[20:47:59 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[20:47:59 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:221)
[20:47:59 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26)
[20:47:59 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13)
[20:47:59 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[20:47:59 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:47:59 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:47:59 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:47:59 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[20:47:59 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
[20:47:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[20:47:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:47:59 WARN]: Caused by: java.lang.IllegalArgumentException: Cannot measure distance between worlds
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.slib.api.server.position.ServerPos3d.distanceSquared(ServerPos3d.kt:50)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.audio.source.VoiceServerProximitySource.sendPacket(VoiceServerProximitySource.kt:85)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.api.server.audio.capture.ProximityServerActivationHelper.onActivationEnd(ProximityServerActivationHelper.kt:82)
[20:47:59 WARN]:        at PlasmoVoice-Paper-2.1.0.jar//su.plo.voice.server.audio.capture.VoiceServerActivationManager.onPlayerSpeakEnd(VoiceServerActivationManager.kt:180)
[20:47:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:47:59 WARN]:        ... 30 more

**Comment by KirieshKaT** [comment]
Измени версию Джавы или скачай подходящую версию мода

**Comment by apehum** [comment]
The issue should be fixed by commit `cfef1645b7247031e40f310540528ff9f18f87f2`, but I'm not entirely sure. Since the issue is hard to reproduce, only testing will confirm if it's really fixed.
You can download the latest build with the fix here: https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.1.

**Comment by apehum** [comment]
Because it wasn't reproduced since then, I assume that issue was fixed.
