### ISSUE TITLE
Спам в консоль сервера

### ISSUE THREAD

**Issue by DedKob1** [plasmoapp/plasmo-voice#72]
Спамит в консоль таким сообщением при каждой активации микрофона игроками, сам чат рабочий. Paper, 1.17.1
[18:55:47 WARN]: java.net.SocketException: Operation not permitted
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(Unknown Source)
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(Unknown Source)
[18:55:47 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(Unknown Source)
[18:55:47 WARN]:        at java.base/java.net.DatagramSocket.send(Unknown Source)
[18:55:47 WARN]:        at su.plo.voice.socket.SocketServerUDP.sendTo(SocketServerUDP.java:70)
[18:55:47 WARN]:        at su.plo.voice.socket.SocketServerUDP.lambda$sendToNearbyPlayers$0(SocketServerUDP.java:54)
[18:55:47 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
[18:55:47 WARN]:        at su.plo.voice.socket.SocketServerUDP.sendToNearbyPlayers(SocketServerUDP.java:41)
[18:55:47 WARN]:        at su.plo.voice.socket.SocketServerUDPQueue.run(SocketServerUDPQueue.java:116)

**Comment by DedKob1** [comment]
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6909276/latest.log)
