### ISSUE TITLE
connecting from same ip

### ISSUE THREAD

**Issue by StBrawler** [plasmoapp/plasmo-voice#84]
so if me and my brother connect me and him turn in to robots if we in 16 blocks but if we walk away we are fine . 

we have good internet so it not that when we fine long as we not near each other

**Comment by StBrawler** [comment]
and thhis 

[00:39:52] [Thread-26/WARN] java.net.SocketException: Operation not permitted
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(Unknown Source)
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(Unknown Source)
[00:39:52] [Thread-26/WARN]     at java.base/sun.nio.ch.DatagramSocketAdaptor.send(Unknown Source)
[00:39:52] [Thread-26/WARN]     at java.base/java.net.DatagramSocket.send(Unknown Source)
[00:39:52] [Thread-26/WARN]     at su.plo.voice.socket.SocketServerUDP.sendTo(SocketServerUDP.java:70)
[00:39:52] [Thread-26/WARN]     at su.plo.voice.socket.SocketServerUDPQueue.keepAlive(SocketServerUDPQueue.java:159)
[00:39:52] [Thread-26/WARN]     at su.plo.voice.socket.SocketServerUDPQueue.run(SocketServerUDPQueue.java:28)

**Comment by KPidS** [comment]
We have no idea what can cause it
