### ISSUE TITLE
[Bug] No sound is input if the microphone changed

### ISSUE THREAD

**Issue by sya-ri** [plasmoapp/plasmo-voice#95]
When you change the microphone source while talking, the microphone will not be input after that.

If I run the command `/vrc`, it gets typed for a while, but then crashes shortly after.

<details>
<summary>Crash log</summary>

```

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2021/10/08 22:17
Description: Rendering screen

java.lang.NullPointerException: Cannot read field "f_91073_" because "this.f_96541_" is null
	at net.minecraft.client.gui.screens.Screen.m_96558_(Screen.java:416) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_7333_(Screen.java:412) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at su.plo.voice.client.gui.VoiceSettingsScreen.m_6305_(VoiceSettingsScreen.java:471) ~[plasmovoice-forge-1.1.0.jar%2354!:1.1.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:304) ~[forge-1.17.1-37.0.78-universal.jar%2359!:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:694) ~[preview_OptiFine_1.17.1_HD_U_H1_pre4.jar%2360!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1270) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:plasmovoice.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:plasmovoice.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.78.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96558_(Screen.java:416) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_7333_(Screen.java:412) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at su.plo.voice.client.gui.VoiceSettingsScreen.m_6305_(VoiceSettingsScreen.java:471) ~[plasmovoice-forge-1.1.0.jar%2354!:1.1.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:304) ~[forge-1.17.1-37.0.78-universal.jar%2359!:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:694) ~[preview_OptiFine_1.17.1_HD_U_H1_pre4.jar%2360!:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: su.plo.voice.client.gui.VoiceSettingsScreen
	Mouse location: Scaled: (278, 207). Absolute: (836.000000, 622.000000)
	Screen size: Scaled: (640, 353). Absolute: (1920, 1057). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 10 total; [LocalPlayer['sya_ri'/3328, l='ClientLevel', x=191.62, y=31.00, z=-160.11], RemotePlayer['yohemal'/3331, l='ClientLevel', x=192.57, y=31.00, z=-160.37], RemotePlayer['tecchan2525'/3333, l='ClientLevel', x=191.92, y=31.00, z=-159.32], RemotePlayer['_mikkom_'/3336, l='ClientLevel', x=184.55, y=32.00, z=-151.90], RemotePlayer['pan_ichi'/3132, l='ClientLevel', x=185.27, y=32.14, z=-148.08], RemotePlayer['Gremaru'/3275, l='ClientLevel', x=188.99, y=31.00, z=-145.79], RemotePlayer['pikuminking'/3195, l='ClientLevel', x=179.90, y=32.12, z=-134.39], RemotePlayer['yuluyulumottii'/3337, l='ClientLevel', x=189.91, y=31.00, z=-149.18], RemotePlayer['Hannyakana_Gm'/3340, l='ClientLevel', x=184.42, y=32.00, z=-149.66], RemotePlayer['nagata_ame1004'/3341, l='ClientLevel', x=183.74, y=32.50, z=-156.42]]
	Chunk stats: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (222,46,-110), Section: (at 14,14,2 in 13,2,-7; chunk contains blocks 208,0,-112 to 223,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 161897 game time, 40292 day time
	Server brand: Airplane
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:467) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2244) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:plasmovoice.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:676) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:plasmovoice.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2355!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.78.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Mod Resources, Default, Ado

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 534985536 bytes (510 MiB) / 1778384896 bytes (1696 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26391.32
	Virtual memory used (MB): 13420.49
	Swap memory total (MB): 10086.46
	Swap memory used (MB): 159.41
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.0.78
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/Ado
	Current Language: 日本語 (日本)
	CPU: 8x Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.17.1_HD_U_H1_pre4
	OptiFine Build: 20210929-213315
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		plasmovoice-forge-1.1.0.jar                       |Plasmo Voice                  |plasmovoice                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.78-universal.jar                |Forge                         |forge                         |37.0.78             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 53988e13-810a-494b-8086-1b033c8d79e1
	FML: 37.0
	Forge: net.minecraftforge:37.0.78

```
</details>

**Comment by Toldoven** [comment]
Is this bug still exists in new versions? We can't reproduce it

**Comment by sya-ri** [comment]
Fixed now! Thank you.
